Support api v3
eduvpn/android pull request #349
Opened 2021-12-05 20:18 UTC by fantostisch

Adds support for [API V3](https://github.com/eduvpn/documentation/blob/v3/API.md) including WireGuard.

This pull requests includes https://github.com/eduvpn/android/pull/347, https://github.com/eduvpn/android/pull/344, https://github.com/eduvpn/android/pull/343 and https://github.com/eduvpn/android/pull/333.

#### Other notable changes

The OpenVPN notification has been replaced with our own notification:
![image](https://user-images.githubusercontent.com/3309700/144757991-ea52680c-2fc7-4b3a-b3d6-aa65fa0d6847.png)
The WireGuard library does not provide a notification, which means we have to create our own, this notification is now also used for OpenVPN.

Most JSON (de)serialization code has been removed and is now generated at compile time using [Kotlin serialization](https://github.com/Kotlin/kotlinx.serialization), which means we do not have to write trivial JSON serialization code anymore. This plugin is officially supported by JetBrains so should be safe to use.

The connection log only shows logs for OpenVPN. Reading the WireGuard logs is possible, but not trivial as it would require starting a logcat process and than parsing its output. A possible solution would be to copy-paste [the relevant code](https://git.zx2c4.com/wireguard-android/tree/ui/src/main/java/com/wireguard/android/activity/LogViewerActivity.kt?h=1.0.20211029&id=1d7d306950082040c41f3b627d57e8c802b4b792#n176) from the WireGuard Android app. I tried to add the WireGuard Android app as a submodule, but I was unable to integrate their gradle setup.

Profile names now support translations. The server does not support this (yet?) but it is specified in the API.

Connecting over an insecure connection (HTTP) was already disabled automatically by Android on Android >=9, but is now also manually disabled on Android >= 6. Redirects from HTTPS to HTTP are now disabled on Android 5 as specified by the API spec.

#### Other notes

There is currently no easy way for the user to know if the app is using OpenVPN or WireGuard. You could check if the connection log is empty or If you have access to the server you can check if the assigned IP is in the WireGuard or OpenVPN range. Another possibility is looking at the logcat. Do we want to show the used VPN protocol?

No online detection is implemented. Who do we connect to?

When checking out this branch, don't forget to also update the submodules which can be done using `git submodule deinit -f . && git submodule update --init --recursive`.

2022-02-24 21:55 UTC, fantostisch commented
To make reviewing a bit easier, I made a diff (https://github.com/fantostisch/android/commit/5bc5bfd50cf22ac9181e6e80987fee9c4929a6bf) that does not include the other pull requests and does not include the conversions to Kotlin. The excluded commits can be seen at https://github.com/eduvpn/android/compare/master...fantostisch:diff4

2022-02-25 15:32 UTC, dzolnai requested changes

2022-02-25 15:32 UTC, dzolnai commented on app/src/main/java/nl/eduvpn/app/service/WireGuardService.kt
> +        // Not necessary for WireGuard
Does WireGuard have its own notification? Or why don't we show it here?

2022-02-25 15:32 UTC, dzolnai commented on app/src/main/java/nl/eduvpn/app/service/WireGuardService.kt
> +        this.errorString = errorString
You should set the error string before notifying the subscribers about the failure

2022-02-25 15:32 UTC, dzolnai commented on app/src/main/java/nl/eduvpn/app/utils/GeneralExtensions.kt
> +val jsonInstance: Json by lazy {
I think this can be better put inside SerializerService

2022-02-28 11:59 UTC, dzolnai commented
I tested the application on this branch, and it seems to work fine, including the WireGuard protocol implementation. 👍

2022-04-13 19:40 UTC, fantostisch commented on app/src/main/java/nl/eduvpn/app/MainActivity.kt
> +    protected lateinit var vpnService: Optional<VPNService>
The MainActivity needs a vpnService, but when opening the app for the first time no vpn connection has been made yet, so we do not know if we need the WireGuard or the OpenVPN service. The empty case is used to indicate that no vpn protocol has been chosen yet.

2022-04-13 20:23 UTC, fantostisch commented on app/src/main/java/nl/eduvpn/app/entity/DiscoveredAPIs.kt
> +        return v2 ?: v3
I changed it to prefer v3, but I think it does not really matter. When we remove v2 support from the Android app, everyone is forced to use v3 API anyway.

2022-04-13 20:34 UTC, fantostisch commented on app/src/main/java/nl/eduvpn/app/entity/exception/EduVPNException.kt
> +    vararg formatArgs: Any?
> Can't you mark this a val, so you don't need line 15?

there seems to be no way to remove line 15, "val vararg" or other variations do not seem to be possible in Kotlin

> I would add a default null value for this param, not all messages need format args.

in the case of a message without parameters, you can just omit the varargs, no null necessary, see for example https://github.com/eduvpn/android/blob/a28efb42742732c0f8f096c50b83e3f21d30bd5e/app/src/main/java/nl/eduvpn/app/service/ConnectionService.kt#L198

2022-04-13 20:43 UTC, fantostisch commented on app/src/main/java/nl/eduvpn/app/service/PreferencesService.kt
> +        private const val STORAGE_VERSION = 3
The master branch shows version 3: https://github.com/eduvpn/android/blob/8fa7c817a3b556d341efdb266940658ac8b32ec1/app/src/main/java/nl/eduvpn/app/service/PreferencesService.java#L55

Somewhere in the git history I did create version 4 and then removed it as it was not necessary.

I do not plan to do a clean start. No upgrade path is necessary, the serialization code was modified, but the data format was not changed. When we remove v2 support can remove the v2 specific data.

2022-04-13 21:23 UTC, fantostisch commented
All feedback/issues without a reply have been fixed, see commits above ^

2022-04-22 11:32 UTC, dzolnai approved these changes

2022-04-22 11:32 UTC, dzolnai commented on app/src/androidTest/java/nl/eduvpn/app/service/PreferencesServiceTest.kt
> +    private var _preferencesService: PreferencesService? = null
You could make these a lateinit var and then you can avoid the force casts

2022-04-22 11:37 UTC, dzolnai commented on app/src/androidTest/java/nl/eduvpn/app/service/PreferencesServiceTest.kt
> +    private var _preferencesService: PreferencesService? = null
Pushed my fix for this on the branch so we can merge

2022-04-22 11:37 UTC, merged